server:
  port: 8762

spring:
  application.name: goodweather-partytime-gateway

management:
  security.enabled: false

security:
  basic.enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true

hystrix.command.default:
  execution:
    timeout:
      enabled: false

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000