FROM java:8-jdk

ENV HOME=/home/ms-openweather-4party

WORKDIR $HOME

ADD wait-for-it.sh wait-for-it.sh

ADD yfwould-ms-openweather-4party/build/libs/ms-openweather-4party.jar ms-openweather-4party.jar