FROM java:8-jdk

ENV HOME=/home/gateway-goodweather-4party

WORKDIR $HOME

ADD wait-for-it.sh wait-for-it.sh

ADD yfwould-gateway-goodweather-4party/build/libs/gateway-goodweather-4party.jar gateway-goodweather-4party.jar