FROM java:8-jdk

ENV HOME=/home/sd-goodweather-partytime

WORKDIR $HOME

ADD wait-for-it.sh wait-for-it.sh

ADD yfwould-sd-goodweather-for-partytime/build/libs/sd-goodweather-partytime.jar sd-goodweather-partytime.jar