FROM java:8-jdk

ENV HOME=/home/ms-openweather-goodweather

WORKDIR $HOME

ADD wait-for-it.sh wait-for-it.sh

ADD yfwould-ms-openweather-goodweather/build/libs/ms-openweather-goodweather.jar ms-openweather-goodweather.jar