version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - goodweather_4party_cluster

  sd-goodweather-4party:
    build:
      context: .
      dockerfile: Dockerfile.SD
    command: ["./wait-for-it.sh", "redis:6379", "--", "java", "-jar", "sd-goodweather-4party.jar"]
    ports:
      - "8761:8761"
    networks:
      - goodweather_4party_cluster

  ms-openweather-4party:
    build:
      context: .
      dockerfile: Dockerfile.OG
    command: ["./wait-for-it.sh", "sd-goodweather-4party:8761", "--", "java", "-jar", "ms-openweather-4party.jar"]
    ports:
      - "8081:8081"
    networks:
      - goodweather_4party_cluster

  ms-spotify-4party:
    build:
      context: .
      dockerfile: Dockerfile.SP
    command: ["./wait-for-it.sh", "ms-openweather-4party:8081", "--", "java", "-jar", "ms-spotify-4party.jar"]
    ports:
      - "8082:8082"
    networks:
      - goodweather_4party_cluster

  ms-goodweather-4party:
    build:
      context: .
      dockerfile: Dockerfile.GP
    command: ["./wait-for-it.sh", "ms-spotify-4party:8082", "--", "java", "-jar", "ms-goodweather-4party.jar"]
    ports:
        - "8080:8080"
    networks:
     - goodweather_4party_cluster

  gateway-goodweather-4party:
    build:
      context: .
      dockerfile: Dockerfile.GGP
    command: ["./wait-for-it.sh", "ms-goodweather-4party:8080", "--", "java", "-jar", "gateway-goodweather-4party.jar"]
    ports:
      - "8762:8762"
    networks:
    - goodweather_4party_cluster

networks:
  goodweather_4party_cluster:
    driver: bridge