version: '3'
services:
  sd-goodweather-for-partytime:
    build:
      context: .
      dockerfile: Dockerfile.SD
  ms-openweather-goodweather:
    build:
      context: .
      dockerfile: Dockerfile.OG
#    depends_on:
#      - sd-goodweather-for-partytime
#  ms-spotify-partytime:
#    build:
#      context: .
#      dockerfile: Dockerfile.SP
#    command: ["./wait-for-it.sh", "sd-goodweather-for-partytime:8761", "--", "java", "-jar", "ms-spotify-partytime.jar"]
#  ms-goodweather-for-partytime:
#    build:
#      context: .
#      dockerfile: Dockerfile.GFP
#    command: ["./wait-for-it.sh", "sd-goodweather-for-partytime:8761", "--", "java", "-jar", "ms-goodweather-for-partytime.jar"]
#  gateway-goodweather-for-partytime:
#    build:
#      context: .
#      dockerfile: Dockerfile.GGFP
#    command: ["./wait-for-it.sh", "sd-goodweather-for-partytime:8761", "--", "java", "-jar", "gateway-goodweather-for-partytime.jar"]