spring:
  application:
    name: goodweather-partytime

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

logging.level:
  com.netflix.eureka: OFF
  com.netflix.discovery: OFF