spring:
  application:
    name: ms-goodweather-4party

server:
  port: 8080

redis:
  host: redis
  port: 6379
  user:
  password:

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://sd-goodweather-4party:8761/eureka

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

logging.level:
  com.netflix.eureka: OFF
  com.netflix.discovery: OFF