spring:
  application:
    name: spotify-partytime

server:
  port: 8082

spotify:
  authorizationAPI:
    url: https://accounts.spotify.com
    clientID: 65a5eb9d97ed46099bb58f28f113178f
    clientSecret: 05173e8c9f0b4087b32c15ca8deace8a
    grantTypeKey: grant_type
    grantTypeValue: client_credentials
    scopeKey: scope
    scopeValue: playlist-read-private
    services:
      authenticate: /api/token
  webAPI:
    url: https://api.spotify.com
    userID: emmanuelframos
    services:
      playlistTracks: /v1/users/{user_id}/playlists/{playlist_id}/tracks

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

logging.level:
  com.netflix.eureka: OFF
  com.netflix.discovery: OFF