spring:
  application:
    name: openweather-goodweather

server:
  port: 8081

openweather:
  url: http://api.openweathermap.org/data/2.5
  params:
    apikeyKey: appid
    apikeyValue: e098fee4b7f030ac0d899595db0b9234
    temperatureUnityKey: units
    temperatureUnityValue: metric
    latKey: lat
    longKey: lon
    cityKey: q
  services:
    weather: /weather

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://sd-goodweather-partytime:8761/eureka

logging.level:
  com.netflix.eureka: OFF
  com.netflix.discovery: OFF